apiVersion: apps/v1
kind: Deployment
metadata:
  name: testkb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testkb
  template:
    metadata:
      labels:
        app: testkb
    spec:
      containers:
        - name: testkb
          image: ajithjose/testkubedc:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: testkb-service
spec:
  type: LoadBalancer
  selector:
    app: testkb
  ports:
    - port: 8080
      targetPort: 8080
      protocol: "TCP"